# Homebrew formula for Fendix — hybrid API and code security scanner.
#
# Tap and install:
#   brew tap Abdel-RahmanSaied/fendix
#   brew install fendix
#
# This file is auto-regenerated by the engine repo's release.yml on
# every `v*` tag. Hand-edits here will be overwritten on the next
# release; edit the canonical copy in the engine repo instead.

class Fendix < Formula
  desc "Hybrid API and code security scanner"
  homepage "https://github.com/Abdel-RahmanSaied/homebrew-fendix"
  license "MIT"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Abdel-RahmanSaied/homebrew-fendix/releases/download/v#{version}/fendix-v#{version}-darwin-arm64"
      sha256 "eb5b1878e8355a6995c0342c0174d71add34e3f7f021aaf67715278ae5c0775c"
    else
      url "https://github.com/Abdel-RahmanSaied/homebrew-fendix/releases/download/v#{version}/fendix-v#{version}-darwin-amd64"
      sha256 "91ab712d6356f05f87f6364f107900b10655ff829e30b93858b6a5f009957929"
    end
  end

  on_linux do
    url "https://github.com/Abdel-RahmanSaied/homebrew-fendix/releases/download/v#{version}/fendix-v#{version}-linux-amd64"
    sha256 "14a33c97bcf6aa2f4d2505e9d2517470acd57d8740c458d71c09a5a837808148"
  end

  depends_on "python@3.11" => :recommended

  def install
    bin.install Dir["fendix-*"].first => "fendix"
  end

  def caveats
    <<~EOC
      Fendix includes an embedded Python engine for whitebox analysis.
      For best results, ensure Python 3 is installed:
        brew install python@3.11

      Quick start:
        fendix scan --url https://api.example.com
        fendix scan --code ./src --spec openapi.yaml --format html -o report.html
    EOC
  end

  test do
    assert_match "fendix version", shell_output("#{bin}/fendix version")
  end
end
