# Homebrew formula for Fendix — hybrid API and code security scanner.
#
# Tap and install:
#   brew tap Abdel-RahmanSaied/fendix
#   brew install fendix
#
# This file is auto-regenerated by the engine repo's release.yml on
# every `v*` tag. Hand-edits here will be overwritten on the next
# release; edit the canonical copy in the engine repo instead.

class Fendix < Formula
  desc "Hybrid API and code security scanner"
  homepage "https://github.com/Abdel-RahmanSaied/homebrew-fendix"
  license "MIT"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Abdel-RahmanSaied/homebrew-fendix/releases/download/v#{version}/fendix-v#{version}-darwin-arm64"
      sha256 "8596698431a92c671bc36ede4659142a1a805e7dbf888b0c91d29e9df56d5223"
    else
      url "https://github.com/Abdel-RahmanSaied/homebrew-fendix/releases/download/v#{version}/fendix-v#{version}-darwin-amd64"
      sha256 "a8349915a9d5e4bdcbec773282361bc16f3ec19c68a6d4675e81b82524fa5cb8"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Abdel-RahmanSaied/homebrew-fendix/releases/download/v#{version}/fendix-v#{version}-linux-arm64"
      sha256 "c900612e996b24558461fa0b278c705d314ac07ddf15915f6701e525084b68ef"
    else
      url "https://github.com/Abdel-RahmanSaied/homebrew-fendix/releases/download/v#{version}/fendix-v#{version}-linux-amd64"
      sha256 "4eda024ae2e03786f9e5d5379acec9e1be26efb44a08613eee1c5ccda9acd379"
    end
  end

  depends_on "python@3.11" => :recommended

  def install
    bin.install Dir["fendix-*"].first => "fendix"
  end

  def caveats
    <<~EOC
      Fendix includes an embedded Python engine for whitebox analysis.
      For best results, ensure Python 3 is installed:
        brew install python@3.11

      Quick start:
        fendix scan --url https://api.example.com
        fendix scan --code ./src --spec openapi.yaml --format html -o report.html
    EOC
  end

  test do
    assert_match "fendix version", shell_output("#{bin}/fendix version")
  end
end
