# Homebrew formula for Fendix — hybrid API and code security scanner.
#
# Tap and install:
#   brew tap Abdel-RahmanSaied/fendix
#   brew install fendix
#
# This file is auto-regenerated by the engine repo's release.yml on
# every `v*` tag. Hand-edits here will be overwritten on the next
# release; edit the canonical copy in the engine repo instead.

class Fendix < Formula
  desc "Hybrid API and code security scanner"
  homepage "https://github.com/Abdel-RahmanSaied/homebrew-fendix"
  license "MIT"
  version "2.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Abdel-RahmanSaied/homebrew-fendix/releases/download/v#{version}/fendix-v#{version}-darwin-arm64"
      sha256 "d9a4f08895a80862e88d33470a8155daa803be8b280f743d3d134496087ef51b"
    else
      url "https://github.com/Abdel-RahmanSaied/homebrew-fendix/releases/download/v#{version}/fendix-v#{version}-darwin-amd64"
      sha256 "82ea29f5a0fee0b57ec63dcfebbf4e99f61dec5f6290cb7808db79cb19e7f318"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Abdel-RahmanSaied/homebrew-fendix/releases/download/v#{version}/fendix-v#{version}-linux-arm64"
      sha256 "e5b7a82958722a588f9d8ee955f31522271b0723acd343ebdc4dae4a5517b75e"
    else
      url "https://github.com/Abdel-RahmanSaied/homebrew-fendix/releases/download/v#{version}/fendix-v#{version}-linux-amd64"
      sha256 "b6a00343933d449d1418bb8790c3530e9f8001c0b3794607ae077bd8e6a58809"
    end
  end

  depends_on "python@3.11" => :recommended

  def install
    bin.install Dir["fendix-*"].first => "fendix"
  end

  def caveats
    <<~EOC
      Fendix includes an embedded Python engine for whitebox analysis.
      For best results, ensure Python 3 is installed:
        brew install python@3.11

      Quick start:
        fendix scan --url https://api.example.com
        fendix scan --code ./src --spec openapi.yaml --format html -o report.html
    EOC
  end

  test do
    assert_match "fendix version", shell_output("#{bin}/fendix version")
  end
end
